### ISSUE TITLE
NetworkError

### ISSUE THREAD

**Issue by blackboxlogic** [matkoniecz/lunar_assembler#118]
Hi, I'm following the directions on https://mapsaregreat.com/osm_to_svg_in_browser/laser_neighbourhood and I'm getting a popup message "TypeError: NetworkError when attempting to fetch resource."
![image](https://user-images.githubusercontent.com/31355456/151280408-f9fadef5-abd3-4c8d-96c2-6c3fb8804192.png)

I'm pretty sure there's nothing wrong with my local network. I don't see any existing github issues mentioning it, so maybe it's just me?

I was just trying it out, looks like an interesting project.

**Comment by matkoniecz** [comment]
Probably problem is with https://github.com/matkoniecz/lunar_assembler/blob/master/lunar_assembler.js#L259 - OpenStreetMap France has issues with their overpass server.

**Comment by matkoniecz** [comment]
Deployed, GitHub pages may have some delay but within 20 minutes fixed version should be available.

Thanks for a report!
