### ISSUE TITLE
wrong link on github homepage

### ISSUE THREAD

**Issue by mnalis** [matkoniecz/lunar_assembler#119]
https://github.com/matkoniecz has a heading that says: 

> My latest project is a [generator of SVG maps from OpenStreetMap data, directly in a browser](https://mapsaregreat.com/svg/).

However, that link (`https://mapsaregreat.com/svg/` has spurious "`/`" at the end, so it returns `404 page not found`.

**Comment by matkoniecz** [comment]
whops, thanks
