### ISSUE TITLE
find JS library for line clipping

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/lunar_assembler#24]
prerequisite for #22

preferably one working on also on geojson areas (NOT 3d.js geojson areas)

**Comment by ceelo777** [comment]
This project looks pretty cool - what exactly do you need for this issue? I'm down to contribute

**Comment by matkoniecz** [comment]
For this one? To find code that would allow clipping lines (the best would be JS library allowing to clip lines and areas, and remove points outside specified area).

Right now generated SVG has invisible parts sticking outside, what is problematic in some kinds of uses (for example in case of using them on a laser cutter). I want to remove and eliminate parts outside selected rectangle.

I found library allowing to clip areas ( https://github.com/matkoniecz/lunar_assembler/issues/22#issuecomment-811355092 ), but from what I see it is not supporting lines (I may be wrong).

See
![screen10](https://user-images.githubusercontent.com/899988/113138055-97040380-9225-11eb-9f2f-0f475dae7c45.png)
