### ISSUE TITLE
Problem with vertical rectangle

### ISSUE THREAD

**Issue by frydrycht** [matkoniecz/lunar_assembler#25]
When user selects rectangle which is "vertical" the tool generates "horizontal" rectangle only with objects contained in selected area. Because of this some objects are missing in generated file.
![osm mapa](https://user-images.githubusercontent.com/40199406/113254067-688a3500-92c6-11eb-8554-e63bb4a143f2.png)

**Comment by matkoniecz** [comment]
OK, I will look into it. It should leave empty margins on left/right and show entire vertical area (as clipping is missing - #22 - it will show objects on marging).

**Comment by matkoniecz** [comment]
@frydrycht Can you post screenshot showing entire area, with "download SVG" button in view? You may need to zoom out view  a bit. Or scroll down.

It seems to me that it is working correctly - see:

![screen12](https://user-images.githubusercontent.com/899988/113257279-ac7f3900-92ca-11eb-94a7-a1399f405188.png)

**Comment by frydrycht** [comment]
If there is a problem with clipping my issue is not valid any more. Telling "missing objects" I thought about objects which are out of the selected area but in area generated on SVG file.

**Comment by matkoniecz** [comment]
In such case it is the same as #22 - it is a known issue that will be fixed

**Comment by matkoniecz** [comment]
I just fixed #22 so this effect should disappear :)
