### ISSUE TITLE
area:highway=steps rendering seems to be missing (or Jubilat crossing needs them to be mapped)

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/lunar_assembler#30]

**Comment by Discostu36** [comment]
`area:highway=service` and `area:highway=traffic_island` are also popular tags that are not rendered yet.

**Comment by matkoniecz** [comment]
`service` is weird, like steps I thought that it is added already

For `traffic_island` I am not sure is there any need to render it, empty area seems fitting in thi case

**Comment by matkoniecz** [comment]
`area:highway=service` is on list of rendered features. If it is not rendered - can you link an affected element? It is best to create a new separate issue for that ( https://github.com/matkoniecz/lunar_assembler/issues/new )

**Comment by Discostu36** [comment]
Weird, it is rendered now. Either a temporary problem or my mistake.
