### ISSUE TITLE
Convince Edge and d3 to cooperate

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/lunar_assembler#57]
> Edge decides to treat it as a regular XML file. Normally it displays the image.
> Adding xmlns="http://www.w3.org/2000/svg" inside the <svg ... > part made it render.

**Comment by matkoniecz** [comment]
I will either need to fiddle with d3 settings or add it manually to generated SVG, as current process generates SVG without that part

**Comment by GoodClover** [comment]
Note that this is only with the downloaded file, it displays fine on the website.

**Comment by matkoniecz** [comment]
should be fixed now, I pushed changes - which will be deployed in about 10 minutes. I will need to switch to computer with Edge to test is it working.

**Comment by matkoniecz** [comment]
tested, fixed
