### ISSUE TITLE
Unbreak touch devices and later investigate further touch/mobile devices

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/lunar_assembler#6]

**Comment by matkoniecz** [comment]
I got report that it seems broken on touch devices, unconfirmed.

**Comment by matkoniecz** [comment]
Confirmed, click and drag is broken. Not tested.

**Comment by matkoniecz** [comment]
If confimed: 

(a) have big button "turn viewport into SVG" (avoids problems with mismatch in proportion, blocks some desired shapes)

(b) ignore touch devices (not viable)

(c) find other selection method

**Comment by Discostu36** [comment]
[In this demo](https://leaflet.github.io/Leaflet.draw/docs/examples-0.7.x/full.html) rectangle drawing also works on touch devices. Maybe you find the difference in the source code.

**Comment by Discostu36** [comment]
But I think that the best solution would actually be a), to have the possibility to convert the bounding box into SVG.

**Comment by matkoniecz** [comment]
> In this demo rectangle drawing also works on touch devices. Maybe you find the difference in the source code.

OK, that is weird. Thanks for checking!

**Comment by matkoniecz** [comment]
Definitely broken.

> In this demo rectangle drawing also works on touch devices. Maybe you find the difference in the source code.

This demo is barely usable but it works. I will investigate what is going on.

**Comment by matkoniecz** [comment]
Unreleased version of Leaflet.draw work. I will replace it as a temporary hack.
