### ISSUE TITLE
Is it broken on Windows (Chrome/Firefox/?)?

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/lunar_assembler#9]

**Comment by Discostu36** [comment]
It does work in Chrome and Firefox on Windows 10

**Comment by matkoniecz** [comment]
Thanks for testing! For now I will consider it as confirmation, especially as there should be no real difference between Linux and Windows in this case.

And touch devices are reported to be borked completely, so that is better target for investigation.
